---
- name: Download MediaWiki files from wikimedia.org
  hosts: all
  remote_user: ansible-user
  become: yes
  gather_facts: no
  tasks:
   - name: Download MediaWiki using get_url
     become: yes
     get_url:
       url: https://releases.wikimedia.org/mediawiki/1.39/mediawiki-1.39.3.tar.gz
       dest: /tmp/
   - name: Create /mediawiki Directory
     become: yes
     file:
       path: /var/lib/mediawiki
       state: directory
   - name: Unarchive the downloaded MediaWorks file
     unarchive:
       src: /tmp/mediawiki-*.tar.gz
       dest: /var/lib/mediawiki
       remote_src: yes      
   - name: Create symbolic link as per the guideline
     file:
      src: "/var/lib/mediawiki/mediawiki-1.39.3"
      dest: "/var/www/mediawiki"
      state: link
   - name: Update Apache2 Enabled Sites
     become: yes
     replace:
       path: /etc/apache2/sites-enabled/000-default.conf
       regexp: 'DocumentRoot \/var\/www\/html$'
       replace: 'DocumentRoot /var/www/html/mediawiki'
  #  - name: Restart Apache2 Service
  #    become: yes
  #    service:
  #      name: apache2
  #      state: restarted
  #      enabled: yes