---
- name: Install all required packages
  hosts: all
  remote_user: ansible-user
  become: yes
  gather_facts: no
  tasks:
  - name: Install latest version of below packages.
    apt:
      name: "{{ item }}"
      state: latest
    loop:
      - apache2
      - mariadb-server
      - php
      - php-mysql
      - libapache2-mod-php
      - php-xml
      - php-mbstring
      - inkscape
      - imagemagick
      - php-intl
      - php-apcu
      - php-gd
      - php-curl
      - php-cli
      - php-bcmath
      - firewalld
      - python3-pip
  - name: Install bottle python package
    pip:
      name: pymysql
  - name: Enable these installed services to start on boot up.
    service:
      name: "{{ item }}"
      state: started
    loop:
      - apache2
      - mariadb
  - name: Create firewall rule for apache service
    firewalld:
      service: http
      zone: public
      permanent: yes
      immediate: yes
      state: enabled
  - name: Create firewall rule for apache service
    firewalld:
      service: https
      zone: public
      permanent: yes
      immediate: yes
      state: enabled	  
  - name: Restart service apache2, in all cases
    service:
      name: apache2
      state: restarted
