---
- name: Create a new database with name wikidatabase
  hosts: all
  remote_user: ansible-user
  become: yes
  tasks:
   - name: Enable MySQL
     service:
      name: mysql
      state: started
      enabled: yes
   - name: Create database for MediaWiki
     community.mysql.mysql_db:
       login_unix_socket: /var/run/mysqld/mysqld.sock
       login_user: "root"
       login_password: '{{ mysql_root_pass }}'
       name: wikidatabase
       state: present
   - name: Create MediaWiki DB user
     community.mysql.mysql_user:
       login_unix_socket: /var/run/mysqld/mysqld.sock
       login_user: "root"
       login_password: '{{ mysql_root_pass }}'
       state: present
       name: wiki
       password: '{{ wiki_pass }}'
       priv:
          'wikidatabase.*': 'ALL,GRANT'