---
- name: Create a new database with name wikidatabase
  hosts: all
  remote_user: ansible-user
  become: yes
  tasks:
   - name: Enable MySQL
     service:
      name: mysql
      state: started
      enabled: yes
   - name: Create database for MediaWiki
     become_user: root
     community.mysql.mysql_db:
       login_unix_socket: /var/run/mysqld/mysqld.sock
       name: wikidatabase
       state: present
   - name: Create MediaWiki DB user
     become_user: root
     community.mysql.mysql_user:
       login_unix_socket: /var/run/mysqld/mysqld.sock
       state: present
       name: wiki
       password: '{{ wiki_pass }}'
       priv:
          'wikidatabase.*:ALL, GRANT'